#!/usr/bin/env python3
"""Settings GUI for the Multi_Background SDDM theme (PySide6 + QML).

* Everything is read/written in this (dev) folder - only "Install" touches /usr/share.
* Whenever `sudo` needs a password, a dialog pops up inside the window (SUDO_ASKPASS
  helper talking to this process over a private unix socket).
"""
import atexit
import json
import mimetypes
import os
import pwd
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import unquote

os.environ.setdefault("QT_QUICK_CONTROLS_STYLE", "Basic")

from PySide6.QtCore import (QObject, Property, Signal, Slot, QProcess,
                            QProcessEnvironment, QTimer, QUrl)
from PySide6.QtGui import QColor, QFontDatabase
from PySide6.QtNetwork import QLocalServer
from PySide6.QtWidgets import QApplication
from PySide6.QtQml import QQmlApplicationEngine

HERE = Path(__file__).resolve().parent
SCRIPT = Path(os.environ.get("MULTIBG_SCRIPT", HERE / "multibg.bash"))
THEME = "Multi_Background"
THEME_DIR = Path(os.environ.get("MULTIBG_THEME_DIR", f"/usr/share/sddm/themes/{THEME}"))
AVATAR_DIR = HERE / "avatars"
FONT_DIR = HERE / "font"
SETTINGS_QML = HERE / "ThemeSettings.qml"
TAP_FILE = Path("/etc/X11/xorg.conf.d/90-sddm-touchpad.conf")

VIDEO_EXT = {".mp4", ".webm", ".mkv", ".mov", ".avi", ".m4v", ".gif"}
IMAGE_EXT = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".avif"}

PALETTE = {
    "bg": "#0d0b08", "side": "#0a0806", "card": "#17130e", "card2": "#1e1912",
    "border": "#2b2418", "gold": "#c9a063", "goldHi": "#e0b878",
    "text": "#f3ead9", "dim": "#9a8f7c", "ok": "#86c28b", "err": "#ff7a7a",
    "warn": "#e3b45a", "field": "#1fffffff", "line": "#33ffffff",
}

# key -> (QML type, default)
SCHEMA = {
    "accent":       ("color",  "#c9a063"),
    "textColor":    ("color",  "#ffffff"),
    "errorColor":   ("color",  "#ff7a7a"),
    "fontFamily":   ("string", ""),
    "clockFormat":  ("string", "HH:mm"),
    "hideAmPm":     ("bool",   False),
    "dateFormat":   ("string", "dddd, MMMM d"),
    "clockSize":    ("int",    160),
    "dateSize":     ("int",    30),
    "showOrbit":    ("bool",   True),
    "dim":          ("real",   0.25),
    "passwordHint": ("string", "Enter Password"),
    "errorText":    ("string", "Incorrect password"),
}
DEFAULTS = {k: v[1] for k, v in SCHEMA.items()}

# Tiny program sudo runs when it needs a password (SUDO_ASKPASS).
ASKPASS_SOURCE = '''#!/usr/bin/env python3
import os, socket, sys
prompt = sys.argv[1] if len(sys.argv) > 1 else "Password:"
try:
    s = socket.socket(socket.AF_UNIX)
    s.connect(os.environ["MULTIBG_SOCK"])
    s.sendall(("%d\\t%s\\n" % (os.getppid(), prompt.replace("\\n", " "))).encode())
    data = b""
    while True:
        chunk = s.recv(4096)
        if not chunk:
            break
        data += chunk
except Exception:
    sys.exit(1)
text = data.decode(errors="replace")
if text.startswith("OK\\n"):
    sys.stdout.write(text[3:].rstrip("\\n") + "\\n")
    sys.exit(0)
sys.exit(1)
'''


# ───────────────────────── settings helpers ─────────────────────────
def coerce(key, value):
    """Force a value from QML into the right type; fall back to the default."""
    typ, default = SCHEMA[key]
    try:
        if typ == "color":
            c = QColor(str(value))
            return c.name() if c.isValid() else default
        if typ == "int":
            lo, hi = (40, 400) if key == "clockSize" else (10, 120)
            return max(lo, min(hi, int(round(float(value)))))
        if typ == "real":
            return max(0.0, min(0.9, round(float(value), 2)))
        if typ == "bool":
            return bool(value)
        return str(value)
    except (TypeError, ValueError):
        return default


def qml_literal(key, value):
    typ = SCHEMA[key][0]
    if typ == "bool":
        return "true" if value else "false"
    if typ in ("int", "real"):
        return repr(value)
    return json.dumps(value)  # valid QML string literal


def render_qml(settings):
    lines = [
        "import QtQuick",
        "",
        "// Generated by multibg_gui.py - safe to edit by hand, the GUI overwrites it on Save.",
        "QtObject {",
    ]
    for key, (typ, _d) in SCHEMA.items():
        lines.append(f"    readonly property {typ:<7} {key}: {qml_literal(key, settings[key])}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def parse_qml(text):
    """Read values back out of ThemeSettings.qml (the single source of truth)."""
    out = {}
    for m in re.finditer(r"readonly\s+property\s+\w+\s+(\w+)\s*:\s*(.+)", text):
        key, lit = m.group(1), m.group(2).strip()
        if key not in SCHEMA:
            continue
        try:
            if lit.startswith("true"):
                val = True
            elif lit.startswith("false"):
                val = False
            elif lit.startswith('"'):
                val = json.JSONDecoder().raw_decode(lit)[0]
            else:
                num = lit.split("//")[0].strip()
                val = float(num) if "." in num else int(num)
            out[key] = coerce(key, val)
        except Exception:
            pass
    return out


def human_size(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024


def kind_of_path(path):
    ext = Path(path).suffix.lower()
    if ext in VIDEO_EXT:
        return "video"
    if ext in IMAGE_EXT:
        return "image"
    mime = mimetypes.guess_type(str(path))[0] or ""
    return "video" if mime.startswith("video/") else "image" if mime.startswith("image/") else "none"


# ───────────────────────── backend ─────────────────────────
class Backend(QObject):
    logged = Signal(str)
    toast = Signal(str, str)            # message, kind (ok|warn|err|info)
    busyChanged = Signal()
    usersChanged = Signal()
    statusChanged = Signal()
    settingsChanged = Signal()
    fontsChanged = Signal()
    sudoStateChanged = Signal()
    previewChanged = Signal()
    done = Signal(bool, str)            # ok, label
    settingsSaved = Signal(bool)
    passwordRequested = Signal(str, bool)   # prompt, retry
    passwordDismissed = Signal()

    def __init__(self):
        super().__init__()
        self._busy = False
        self._rev = 0
        self._label = ""
        self._proc = None
        self._prev = None
        self._cancelled = False
        self._save_pending = False
        self._settings = self._load_settings()

        # private temp dir: askpass helper + socket + thumbnails
        self._tmp = Path(tempfile.mkdtemp(prefix="multibg-"))
        os.chmod(self._tmp, 0o700)
        atexit.register(lambda: shutil.rmtree(self._tmp, ignore_errors=True))
        self._askpass = self._tmp / "askpass.py"
        self._askpass.write_text(ASKPASS_SOURCE)
        os.chmod(self._askpass, 0o700)
        self._sock_path = str(self._tmp / "ask.sock")

        # password state
        self._pw = ""
        self._deny = False
        self._last_ppid = ""
        self._asking = None
        self._queue = []
        self._server = QLocalServer(self)
        QLocalServer.removeServer(self._sock_path)
        self._server.setSocketOptions(QLocalServer.UserAccessOption)
        if not self._server.listen(self._sock_path):
            print("warning: askpass socket failed:", self._server.errorString(), file=sys.stderr)
        self._server.newConnection.connect(self._on_connection)

    # ───────── sudo password pop-up plumbing ─────────
    def _on_connection(self):
        while self._server.hasPendingConnections():
            sock = self._server.nextPendingConnection()
            sock.readyRead.connect(lambda s=sock: self._on_request(s))
            sock.disconnected.connect(lambda s=sock: self._on_gone(s))

    def _on_request(self, sock):
        if not sock.canReadLine():
            return
        line = bytes(sock.readLine()).decode(errors="replace").rstrip("\n")
        ppid, _, prompt = line.partition("\t")
        # Same sudo process asking twice = the password we gave it was wrong.
        retry = bool(ppid) and ppid == self._last_ppid
        self._last_ppid = ppid
        if self._deny:
            return self._reply(sock, None)
        if retry and self._pw:
            self._pw = ""
            self.sudoStateChanged.emit()
        if self._pw:
            return self._reply(sock, self._pw)
        if self._asking is not None:
            self._queue.append((sock, retry, prompt))
            return
        self._ask(sock, retry, prompt)

    def _ask(self, sock, retry, prompt):
        self._asking = sock
        self.passwordRequested.emit(prompt.strip() or "Password:", retry)

    def _on_gone(self, sock):
        self._queue = [q for q in self._queue if q[0] is not sock]
        if sock is self._asking:
            self._asking = None
            self.passwordDismissed.emit()
            self._next_queued()

    def _reply(self, sock, pw):
        try:
            sock.write(b"NO\n" if pw is None else b"OK\n" + pw.encode() + b"\n")
            sock.flush()
            sock.disconnectFromServer()
        except Exception:
            pass

    def _next_queued(self):
        if self._asking is not None or not self._queue:
            return
        sock, retry, prompt = self._queue.pop(0)
        if self._deny:
            self._reply(sock, None)
            return self._next_queued()
        if self._pw:
            self._reply(sock, self._pw)
            return self._next_queued()
        self._ask(sock, retry, prompt)

    @Slot(str)
    def submitPassword(self, pw):
        sock, self._asking = self._asking, None
        if sock is None:
            return
        self._pw = pw
        self._reply(sock, pw)
        self.sudoStateChanged.emit()
        self._next_queued()

    @Slot()
    def cancelPassword(self):
        self._deny = True
        sock, self._asking = self._asking, None
        if sock is not None:
            self._reply(sock, None)
        for s, _r, _p in self._queue:
            self._reply(s, None)
        self._queue = []
        self.logged.emit("! sudo password prompt cancelled")

    @Slot()
    def forgetPassword(self):
        self._pw = ""
        subprocess.run(["sudo", "-K"], capture_output=True)
        self.sudoStateChanged.emit()
        self.toast.emit("Admin password forgotten", "info")

    # ───────── environment ─────────
    def _env(self):
        env = QProcessEnvironment.systemEnvironment()
        env.insert("SUDO_ASKPASS", str(self._askpass))
        env.insert("MULTIBG_SOCK", self._sock_path)
        return env

    # ───────── settings persistence ─────────
    def _load_settings(self):
        data = dict(DEFAULTS)
        try:
            data.update(parse_qml(SETTINGS_QML.read_text()))
        except Exception:
            pass
        return data

    # ───────── properties ─────────
    @Property(bool, notify=busyChanged)
    def busy(self):
        return self._busy

    @Property(str, constant=True)
    def scriptDir(self):
        return str(HERE)

    @Property(str, constant=True)
    def themeDir(self):
        return str(THEME_DIR)

    @Property(int, notify=usersChanged)
    def rev(self):
        return self._rev

    @Property(bool, notify=sudoStateChanged)
    def sudoUnlocked(self):
        return bool(self._pw)

    @Property(bool, notify=previewChanged)
    def previewRunning(self):
        return self._prev is not None and self._prev.state() != QProcess.NotRunning

    @Property(bool, notify=statusChanged)
    def themeInstalled(self):
        return THEME_DIR.is_dir()

    @Property(bool, notify=statusChanged)
    def folderWritable(self):
        return os.access(HERE, os.W_OK)

    @Property(bool, notify=statusChanged)
    def tapEnabled(self):
        return TAP_FILE.exists()

    @Property(str, notify=statusChanged)
    def displayServer(self):
        ds = "x11 (default)"
        for p in [Path("/etc/sddm.conf")] + sorted(Path("/etc/sddm.conf.d").glob("*.conf")):
            try:
                for line in p.read_text().splitlines():
                    if line.strip().lower().startswith("displayserver="):
                        ds = line.split("=", 1)[1].strip() or ds
            except Exception:
                pass
        return ds

    @Property(str, notify=statusChanged)
    def activeTheme(self):
        cur = "(not set)"
        for p in [Path("/etc/sddm.conf")] + sorted(Path("/etc/sddm.conf.d").glob("*.conf")):
            try:
                for line in p.read_text().splitlines():
                    if line.strip().startswith("Current="):
                        cur = line.split("=", 1)[1].strip() or cur
            except Exception:
                pass
        return cur

    @Property("QVariantList", notify=statusChanged)
    def checks(self):
        out = []

        def add(name, ok, detail="", level=None):
            out.append({"name": name, "ok": bool(ok), "detail": detail,
                        "level": level or ("ok" if ok else "bad")})

        add("Theme script", SCRIPT.is_file(), str(SCRIPT))
        add("Main.qml", (HERE / "Main.qml").is_file(), "the login screen itself")
        add("metadata.desktop", (HERE / "metadata.desktop").is_file(),
            "SDDM ignores a theme folder without it", None if (HERE / "metadata.desktop").is_file() else "warn")
        add("Folder writable", os.access(HERE, os.W_OK), str(HERE),
            None if os.access(HERE, os.W_OK) else "warn")
        im = shutil.which("magick") or shutil.which("convert")
        ff = shutil.which("ffmpeg")
        add("ImageMagick", im, "best avatar / image conversion",
            None if im else ("warn" if ff else "bad"))
        add("ffmpeg", ff, "video thumbnails, avatar fallback", None if ff else "warn")
        add("sudo", shutil.which("sudo"), "needed for install and tap-to-click")
        g = shutil.which("sddm-greeter-qt6") or shutil.which("sddm-greeter")
        add("sddm-greeter", g, "needed for Preview", None if g else "warn")
        qml_dirs = [Path(p) for p in ("/usr/lib/qt6/qml", "/usr/lib64/qt6/qml",
                                      "/usr/lib/x86_64-linux-gnu/qt6/qml")]
        existing = [d for d in qml_dirs if d.is_dir()]
        if existing:
            has = lambda m: any((d / m).is_dir() for d in existing)  # noqa: E731
            add("Qt5Compat (greeter)", has("Qt5Compat"), "Main.qml imports Qt5Compat.GraphicalEffects")
            add("QtMultimedia (greeter)", has("QtMultimedia"), "needed for video backgrounds")
        else:
            add("Qt QML modules", False, "could not verify Qt5Compat / QtMultimedia", "warn")
        return out

    @Property("QVariantList", notify=usersChanged)
    def users(self):
        out = []
        for u in pwd.getpwall():
            if not (1000 <= u.pw_uid <= 60000):
                continue
            av = AVATAR_DIR / f"{u.pw_name}.png"
            url, has = "", av.is_file()
            if has:
                url = QUrl.fromLocalFile(str(av)).toString() + f"?v={av.stat().st_mtime_ns}"
            out.append({"login": u.pw_name,
                        "name": (u.pw_gecos.split(",")[0] or u.pw_name),
                        "avatar": url, "hasAvatar": has})
        return out

    @Property("QVariantMap", notify=settingsChanged)
    def settings(self):
        return dict(self._settings)

    @Property("QVariantMap", constant=True)
    def defaults(self):
        return dict(DEFAULTS)

    @Property("QVariantMap", constant=True)
    def pal(self):
        return dict(PALETTE)

    @Property("QVariantList", notify=fontsChanged)
    def fontFiles(self):
        if not FONT_DIR.is_dir():
            return []
        return sorted(p.name for p in FONT_DIR.iterdir()
                      if p.suffix.lower() in (".ttf", ".otf"))

    @Property(str, notify=fontsChanged)
    def fontUrl(self):
        files = self.fontFiles
        return QUrl.fromLocalFile(str(FONT_DIR / files[0])).toString() if files else ""

    @Property("QVariantList", constant=True)
    def systemFonts(self):
        return list(QFontDatabase.families())

    # ───────── small helpers for QML ─────────
    @Slot(str, result=str)
    def localPath(self, url):
        return unquote(QUrl(url).toLocalFile() or url)

    @Slot(str, result=str)
    def fileUrl(self, path):
        return QUrl.fromLocalFile(path).toString() if path else ""

    @Slot(str, result=str)
    def fileKind(self, path):
        return kind_of_path(path) if path else "none"

    @Slot(str, result="QVariantMap")
    def bgInfo(self, name):
        for ext, kind in (("mp4", "video"), ("jpg", "image")):
            f = HERE / f"{name}.{ext}"
            if f.is_file():
                st = f.stat()
                url = QUrl.fromLocalFile(str(f)).toString()
                if kind == "image":
                    url += f"?v={st.st_mtime_ns}"
                return {"kind": kind, "path": str(f), "url": url, "size": human_size(st.st_size)}
        return {"kind": "none", "path": "", "url": "", "size": ""}

    @Slot(str, result=str)
    def thumbnail(self, path):
        """First frame of a video as a png url (fallback when playback is not possible)."""
        ff = shutil.which("ffmpeg")
        src = Path(path)
        if not ff or not src.is_file():
            return ""
        out = self._tmp / f"thumb-{abs(hash((str(src), src.stat().st_mtime_ns)))}.png"
        if not out.is_file():
            for ss in ("1", "0"):
                try:
                    subprocess.run([ff, "-y", "-loglevel", "error", "-ss", ss, "-i", str(src),
                                    "-frames:v", "1", "-vf", "scale=960:-2", str(out)],
                                   capture_output=True, timeout=20)
                except Exception:
                    pass
                if out.is_file() and out.stat().st_size > 0:
                    break
        return QUrl.fromLocalFile(str(out)).toString() if out.is_file() else ""

    # ───────── running the bash script ─────────
    @Slot(list, str)
    def run(self, args, label):
        if self._busy:
            self.toast.emit("Another task is still running", "warn")
            return
        if not SCRIPT.is_file():
            self.toast.emit(f"Script not found: {SCRIPT}", "err")
            return
        self._deny = False
        self._last_ppid = ""
        self._cancelled = False
        self._label = label
        self._set_busy(True)
        self.logged.emit("$ multibg.bash " + " ".join(map(str, args)))
        p = QProcess(self)
        p.setProcessEnvironment(self._env())
        p.setProcessChannelMode(QProcess.MergedChannels)
        p.readyReadStandardOutput.connect(
            lambda: self._emit_output(p))
        p.finished.connect(lambda code, _s: self._finished(code))
        p.errorOccurred.connect(self._proc_error)
        self._proc = p
        p.start("bash", [str(SCRIPT)] + [str(a) for a in args])
        p.closeWriteChannel()

    def _emit_output(self, p):
        text = bytes(p.readAllStandardOutput()).decode(errors="replace").rstrip()
        if text:
            self.logged.emit(text)

    def _proc_error(self, err):
        if err == QProcess.FailedToStart and self._busy:
            self.logged.emit("✘ could not start bash")
            self._set_busy(False)
            self.done.emit(False, self._label)

    @Slot()
    def cancel(self):
        if self._proc is not None and self._busy:
            self._cancelled = True
            self.logged.emit("… cancelling")
            self._proc.terminate()
            QTimer.singleShot(2500, lambda: self._proc.kill()
                              if self._proc is not None and self._proc.state() != QProcess.NotRunning else None)
            self.cancelPassword()

    def _set_busy(self, v):
        self._busy = v
        self.busyChanged.emit()

    def _finished(self, code):
        self._set_busy(False)
        ok = (code == 0) and not self._cancelled
        self.logged.emit("✔ done" if ok else ("■ cancelled" if self._cancelled else f"✘ exited with code {code}"))
        self._rev += 1
        self.usersChanged.emit()
        self.statusChanged.emit()
        self.fontsChanged.emit()
        if self._save_pending:
            self._save_pending = False
            self.settingsSaved.emit(ok)
        self.done.emit(ok, "__cancelled__" if self._cancelled else self._label)

    # ───────── look settings ─────────
    @Slot("QVariantMap")
    def saveSettings(self, values):
        new = dict(DEFAULTS)
        for k in SCHEMA:
            if k in values:
                new[k] = coerce(k, values[k])
        text = render_qml(new)
        self._settings = new
        try:                                      # atomic write
            tmp = SETTINGS_QML.with_suffix(".qml.tmp")
            tmp.write_text(text)
            os.replace(tmp, SETTINGS_QML)
            self.logged.emit(f"+ saved look settings -> {SETTINGS_QML}")
            self.settingsChanged.emit()
            self.settingsSaved.emit(True)
        except PermissionError:                   # folder owned by root: go through the script (sudo pop-up)
            stage = self._tmp / "ThemeSettings.qml"
            stage.write_text(text)
            self._save_pending = True
            self.settingsChanged.emit()
            self.run(["-put", str(stage), str(SETTINGS_QML)], "Settings saved")
        except Exception as e:  # noqa: BLE001
            self.logged.emit(f"! could not save settings: {e}")
            self.toast.emit("Could not save settings (see Activity)", "err")
            self.settingsSaved.emit(False)

    @Slot()
    def reloadSettings(self):
        self._settings = self._load_settings()
        self.settingsChanged.emit()

    # ───────── preview (sddm-greeter in test mode on THIS folder) ─────────
    @Slot()
    def startPreview(self):
        if self.previewRunning:
            return
        greeter = shutil.which("sddm-greeter-qt6") or shutil.which("sddm-greeter")
        if not greeter:
            self.toast.emit("sddm-greeter not found (install the sddm package)", "err")
            return
        p = QProcess(self)
        p.setProcessChannelMode(QProcess.MergedChannels)
        p.readyReadStandardOutput.connect(lambda: self._emit_output(p))
        p.finished.connect(lambda *_: self._preview_ended())
        p.errorOccurred.connect(lambda *_: self._preview_ended())
        self._prev = p
        self.logged.emit(f"$ {Path(greeter).name} --test-mode --theme {HERE}")
        p.start(greeter, ["--test-mode", "--theme", str(HERE)])
        self.previewChanged.emit()

    def _preview_ended(self):
        self.previewChanged.emit()

    @Slot()
    def stopPreview(self):
        if self.previewRunning:
            self._prev.terminate()
            QTimer.singleShot(1500, lambda: self._prev.kill() if self.previewRunning else None)

    @Slot()
    def refreshStatus(self):
        self.statusChanged.emit()
        self.usersChanged.emit()
        self.fontsChanged.emit()

    @Slot()
    def shutdown(self):
        self.stopPreview()
        if self._proc is not None and self._busy:
            self._proc.kill()


def main():
    app = QApplication(sys.argv)
    app.setApplicationName("Multi_Background settings")
    engine = QQmlApplicationEngine()
    backend = Backend()
    app.aboutToQuit.connect(backend.shutdown)
    ctx = engine.rootContext()
    ctx.setContextProperty("backend", backend)
    ctx.setContextProperty("Pal", PALETTE)
    engine.load(QUrl.fromLocalFile(str(HERE / "SettingsGui.qml")))
    if not engine.rootObjects():
        sys.exit(1)
    code = app.exec()
    del engine          # tear the QML side down before the backend it talks to
    del backend
    sys.exit(code)


if __name__ == "__main__":
    main()
