import QtQuick

// Generated by multibg_gui.py - safe to edit by hand, the GUI overwrites it on Save.
QtObject {
    readonly property color   accent: "#c9a063"
    readonly property color   textColor: "#ffffff"
    readonly property color   errorColor: "#ff7a7a"
    readonly property string  fontFamily: ""
    readonly property string  clockFormat: "HH:mm"
    readonly property bool    hideAmPm: false
    readonly property string  dateFormat: "dddd, MMMM d"
    readonly property int     clockSize: 160
    readonly property int     dateSize: 30
    readonly property bool    showOrbit: true
    readonly property real    dim: 0.25
    readonly property string  passwordHint: "Enter Password"
    readonly property string  errorText: "Incorrect password"
}
